namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_LAYER_BASIN: string;
    NEXT_PUBLIC_LAYER_BASIN_PWS: string;
    NEXT_PUBLIC_LAYER_STATES: string;
    NEXT_PUBLIC_LAYER_PCA: string;

    NEXT_PUBLIC_LAYER_COUNTIES: string;

    NEXT_PUBLIC_LAYER_AZ_PARKS: string;
    NEXT_PUBLIC_LAYER_AZ_RESERVATIONS: string;
    NEXT_PUBLIC_LAYER_AZ_HIGHWAYS: string;

    NEXT_PUBLIC_LAYER_AZ_OZONE: string;
    NEXT_PUBLIC_LAYER_AZ_PM10: string;
    NEXT_PUBLIC_LAYER_AZ_PM25: string;
    NEXT_PUBLIC_LAYER_AZ_SULFUR_DIOXIDE: string;
    NEXT_PUBLIC_LAYER_AZ_LEAD: string;

    NEXT_PUBLIC_LAYER_AZ_LICENSED_FACILITIES: string;
    NEXT_PUBLIC_LAYER_AZ_FAST_FOODS: string;
    NEXT_PUBLIC_LAYER_AZ_CONVENIENCE_GAS_STORES: string;
    NEXT_PUBLIC_LAYER_AZ_GROCERY_STORES: string;
    NEXT_PUBLIC_LAYER_AZ_WIC: string;
    NEXT_PUBLIC_LAYER_AZ_WIC_VENDORS: string;

    NEXT_PUBLIC_LAYER_HAZARDOUS_WASTE_TSD: string;
    NEXT_PUBLIC_LAYER_HAZARDOUS_WASTE_LQG: string;

    NEXT_PUBLIC_LAYER_SUPERFUND_POINT: string;
    NEXT_PUBLIC_LAYER_SUPERFUND_POLY: string;

    NEXT_PUBLIC_LAYER_BROWNFIELD_SITE_POLY: string;
    NEXT_PUBLIC_LAYER_BROWNFIELD_SITE_POINT: string;

    NEXT_PUBLIC_LAYER_PRIVATE_SCHOOL: string;
    NEXT_PUBLIC_LAYER_PUBLIC_SCHOOL: string;
  }
}
