import type { Metadata } from 'next';
import './globals.css';
import { setAssetPath } from '@esri/calcite-components/dist/components';
// CDN hosted assets
setAssetPath('https://js.arcgis.com/calcite-components/2.11.1/assets');
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
